In [1]:
import numpy as np
import pandas as pd

In [2]:
# 1. How to Creating a 3x3 Identity Matrix with Float Data Type?
array1=np.arange(9, dtype=float).reshape(3,3)
print(array1)

[[0. 1. 2.]
 [3. 4. 5.]
 [6. 7. 8.]]


In [3]:
# 2. Create a 1D Array with Random Values between 0 and 1.
Array1D=np.random.rand(1)
print(Array1D)

[0.12309632]


In [4]:
# 3. Create a 2D Array with Random Integer Values.
Array2D=np.random.randint(1,5,(3,3))
print(Array2D)

[[3 4 3]
 [4 2 1]
 [4 1 3]]


In [5]:
# 4. Creating an Array Using a Custom Function.
def custom_func(i, j): #(i or j) value 0 to n tak
    return i + j

arr = np.fromfunction(custom_func, (5, 5), dtype=int) #fromfunction for value getting from the funti
print(arr)
custom_func(2,5)


[[0 1 2 3 4]
 [1 2 3 4 5]
 [2 3 4 5 6]
 [3 4 5 6 7]
 [4 5 6 7 8]]


7

In [6]:
# 5. Reshaping a 1D Array into a 2D Array
array1d=np.array([1,2,3,4,5,6])
array2d=array1d.reshape(2,3)
print(array2d)


[[1 2 3]
 [4 5 6]]


In [7]:
# 6.How to Creating a 3x3 Array of Ones?
arr=np.ones((3,3))
print(arr)


[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [8]:

# 7. How to get the common items between two pythons
# NumPy? Input:
a = np. array ([1,2,3,2,3,4,3,4,5,6])
b = np. array ([7,2,10,2,7,4,9,4,9,8])
# Expected Output:
# array ([2, 4])
c=np.intersect1d(a,b)
c

array([2, 4])

In [9]:

# 8. From array a remove all items present in
# array b Input:
a = np. array ([1,2,3,4,5])
b = np. array ([5,6,7,8,9])
# Expected Output:
# array ([1,2,3,4]
c=np.setdiff1d(a,b)
print(c)

[1 2 3 4]


In [10]:
# 9. Limit the number of items printed in python NumPy array a to a maximum of
# 6 elements.
# a = np. arrange (15)
# Expected Output:
# array ([ 0, 1, 2, ..., 12, 13, 14]

In [11]:
# 10. Drop all nan values from a 1D NumPy 
array1d=np. array ([1,2,3, np.nan,5,6,7, np.nan]) 
array1d_clean = array1d[~np.isnan(array1d)]
array1d_clean

array([1., 2., 3., 5., 6., 7.])

In [12]:
 # 11. Question: Create a 1D NumPy array of the first 20 natural numbers and a 
# 2D NumPy array of shape (4, 5) with values ranging from 1 to 20.
array1d=np.array([1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20])
array2d=array1d.reshape(4,5)
array2d

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20]])

In [13]:
# 12. Question: Given a 3D NumPy array of shape (2, 3, 4), find its shape, size, number of dimensions, and data type. 
# Change its data type to float64 and verify the change.
array3d=np.arange(24).reshape(2,3,4)
print(array3d)
print(array3d.shape)
print(array3d.size)
print(array3d.ndim)
print(array3d.dtype)
changed=(array3d.astype(float))
print(changed)
print(changed.dtype)



[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
(2, 3, 4)
24
3
int64
[[[ 0.  1.  2.  3.]
  [ 4.  5.  6.  7.]
  [ 8.  9. 10. 11.]]

 [[12. 13. 14. 15.]
  [16. 17. 18. 19.]
  [20. 21. 22. 23.]]]
float64


In [14]:
# 13. Question: Reshape a 1D array of 12 elements into a 3x4 2D array and then 
# flatten it back into a 1D array using ravel (). Verify that the flattened array matches the original. 
array1d=np.arange(12)
print(array1d)
array2d=array1d.reshape(3,4)
print(array2d)
flattened_array = array2d.ravel()
print(flattened_array)
print(np.array_equal(array1d,flattened_array))


[ 0  1  2  3  4  5  6  7  8  9 10 11]
[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[ 0  1  2  3  4  5  6  7  8  9 10 11]
True


In [15]:
# 14. Question: Given two arrays, a = np. array ([1, 2, 3]) and b = np. array ([4,5, 6]), perform element-wise addition, subtraction,
# multiplication, and division. Explain the behavior when dividing by zero.
a = np. array ([1, 2, 3]) 
b = np. array ([4,5, 6])
print(a)
print(b)
c=a+b
d=a-b
e=a*b
f=a/b
g=a/0
print(c)
print(d)
print(e)
print(f)
print(g)

[1 2 3]
[4 5 6]
[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]
[inf inf inf]


C:\Users\Swapnil\AppData\Local\Temp\ipykernel_25740\1840070595.py:11: RuntimeWarning: divide by zero encountered in divide
  g=a/0


In [16]:
# 15. Question: cand a 1D array of length 3. Perform element-wise addition using broadcasting.
# Explain how broadcasting rules apply in this scenario. 
array1D=np.array([10, 20, 30])

array2D=np.array([[1],[2],[3]])
print(array1D)
print(array2D)
Broadcasted=array1D+array2D
print(Broadcasted)


[10 20 30]
[[1]
 [2]
 [3]]
[[11 21 31]
 [12 22 32]
 [13 23 33]]


In [17]:
# 16. Question: Generate a random 2D array of integers between 0 and 10. Use conditional operators to create a Boolean mask identifying
# elements greater than 5. Replace all elements greater than 5 with the value 5.
array2D=np.random.randint(0,11,(3,3))
print(array2D)
comparision=array2D>5
print(comparision)
array2D[comparision]=5
print(array2D)


[[8 7 9]
 [6 2 1]
 [9 0 5]]
[[ True  True  True]
 [ True False False]
 [ True False False]]
[[5 5 5]
 [5 2 1]
 [5 0 5]]


In [18]:
# 17. Question: Given a 4x4 array of random integers, use indexing and slicing to extract: 
# o The entire second row 
# o The last column 
# o The subarray consisting of the first two rows and first two columns 
array=np.random.randint(1,11,(4,4)).astype(int)
print(array)
print(array[1])
print(array[3])
print(array[0:2,0:2])


[[ 7  2  6 10]
 [ 6  4  7  6]
 [ 2  7  8  8]
 [ 1  6  1  9]]
[6 4 7 6]
[1 6 1 9]
[[7 2]
 [6 4]]


In [19]:
# 18. Question: Describe a practical example where NumPy can be used in EDA, AI, ML, and DL, and implement a NumPy solution for a simple task in each area.
# 1. EDA (Exploratory Data Analysis): 
# Use:Summarizing data (mean, std, etc.)  
# Example Task:Calculate mean & std of sample data  
# data = np.array([10, 20, 30, 40, 50])
# print("Mean:", np.mean(data))
# print("Std Dev:", np.std(data))

# 2. AI (Artificial Intelligence):
# Use:Rule-based logic operations  
# Example Task:Apply condition-based decision
# scores = np.array([0.2, 0.8, 0.6])
# decision = scores > 0.5
# print("Decision:", decision)  

# 3. ML (Machine Learning): 
# Use:Data normalization before training  
# Example Task:Min-Max Scaling
# features = np.array([2, 4, 6, 8])
# scaled = (features - np.min(features)) / (np.max(features) - np.min(features))
# print("Scaled:", scaled)

# 4. DL (Deep Learning):  
# Use:Matrix ops in neural nets  
# Example Task:Matrix multiplication (dot product)
# X = np.array([[1, 2], [3, 4]])
# W = np.array([[0.5], [1]])
# output = np.dot(X, W)
# print("Dot Product (DL output):\n", output)


In [20]:
# 19. Question: Create a random 4x4 matrix and use NumPy to compute its eigenvalues and eigenvectors. Verify the eigenvalues by reconstructing the 
# matrix. 
randarray=np.random.randint(1,11,(4,4))
print(randarray)
#❓❓❓❓❓❓❓❓❓❓❓❓❓❓❓❓❓ sir se puchna h

[[ 8  8 10  7]
 [ 5  4  6 10]
 [ 5  4  1  3]
 [ 5  3  9  8]]


In [21]:
# 20. Question: Create a 1D array of 27 elements and reshape it into a 3x3x3 3D array. Flatten it back into a 1D array and compare the flattened array 
# with the original. 
array1D=np.arange(27)
print(array1D)
aranged=array1D.reshape(3,3,3)
print(aranged)
flattend=aranged.ravel()
print(flattend)



[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]
[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]]

 [[ 9 10 11]
  [12 13 14]
  [15 16 17]]

 [[18 19 20]
  [21 22 23]
  [24 25 26]]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26]


In [22]:
# 21. Question: Perform matrix multiplication of two 2D arrays using np.dot ()and @. Compare the results and performance of both methods using a large 
# dataset. 
array2D_1=np.arange(6).reshape(2,3)
print(array2D_1)
array2D_2=np.arange(8).reshape(2,4)
print(array2D_2)


[[0 1 2]
 [3 4 5]]
[[0 1 2 3]
 [4 5 6 7]]


In [23]:
# 22. Question: Create a 3D array of shape (2, 1, 4) and a 2D array of shape (4, 1). Perform an element-wise operation using broadcasting
# and explain the result. Use np. new axis to achieve the same result without broadcasting.
array3D=np.arange(8).reshape(2,1,4)
print(array3D)
array2D=np.arange(4).reshape(4,1)
print(array2D)
new=array3D+array2D
print(new)



[[[0 1 2 3]]

 [[4 5 6 7]]]
[[0]
 [1]
 [2]
 [3]]
[[[ 0  1  2  3]
  [ 1  2  3  4]
  [ 2  3  4  5]
  [ 3  4  5  6]]

 [[ 4  5  6  7]
  [ 5  6  7  8]
  [ 6  7  8  9]
  [ 7  8  9 10]]]


In [24]:
# 23. Question: Generate a 2D array of random floats between 0 and 1. Use conditional operators to create a Boolean mask for values less than 0.5. 
# Replace these values with their squares and leave the rest unchanged. 
Array2D=np.random.rand(2,3)
print(Array2D)
mask=Array2D<0.5
print(mask)
Array2D[mask]=Array2D[mask]**2
print(Array2D)


[[0.84842365 0.78728928 0.07317702]
 [0.66296035 0.27535947 0.79993699]]
[[False False  True]
 [False  True False]]
[[0.84842365 0.78728928 0.00535488]
 [0.66296035 0.07582284 0.79993699]]


In [25]:
# 24. Question: Given a 5x5 array of sequential integers, use slicing to: 
# o Extract the diagonal elements 
# o Replace the elements of the middle row with zeros 
# o Flip the array vertically and horizontally 
Array=np.arange(25).reshape(5,5)
print(Array)




[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


In [37]:
# 25. Question: Create a 4D array of shape (2, 3, 4, 5) with random integers. Use advanced slicing to extract a subarray and compute the mean along a 
# specified axis. 
Array4D=np.random.randint(0,101,(2,3,4,5))
print(Array4D)



[[[[16 86 51 39 67]
   [36 11 65 79 41]
   [64 80 33 47 37]
   [58 29 60 56 22]]

  [[83 46 24 15 12]
   [46 77 91 75 60]
   [ 8 40 57 90 55]
   [67 97 51 78  8]]

  [[17 15 26 52 29]
   [14 85 96  6 13]
   [81 50 96 97 48]
   [92 18 73 50 92]]]


 [[[33 83 61 47 26]
   [ 7 75 43 21 95]
   [30 12 38 32  1]
   [ 0 87  0 11 61]]

  [[86 98 43 79 39]
   [88 94 27 39 60]
   [91 92 80 54 69]
   [64 84 47 12 56]]

  [[81  4 31  1 94]
   [ 2 28 18 12  6]
   [45 78 38 55 18]
   [12 26 62 29 71]]]]
[[[[64 80 33]
   [58 29 60]]

  [[ 8 40 57]
   [67 97 51]]]


 [[[30 12 38]
   [ 0 87  0]]

  [[91 92 80]
   [64 84 47]]]]


In [44]:
# 26. Question:Given an array of shape(10, 20),reshape it to (20, 10) and (5, 40). Discuss the impact on the array's shape, size, and dimensionality.
Array=np.arange(200).reshape(10,20)
print(Array,"=============")
array=Array.reshape(20,10)
print(array,"=============")
new_array=array.reshape(5,40)
print(new_array,"===========")


[[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
   18  19]
 [ 20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35  36  37
   38  39]
 [ 40  41  42  43  44  45  46  47  48  49  50  51  52  53  54  55  56  57
   58  59]
 [ 60  61  62  63  64  65  66  67  68  69  70  71  72  73  74  75  76  77
   78  79]
 [ 80  81  82  83  84  85  86  87  88  89  90  91  92  93  94  95  96  97
   98  99]
 [100 101 102 103 104 105 106 107 108 109 110 111 112 113 114 115 116 117
  118 119]
 [120 121 122 123 124 125 126 127 128 129 130 131 132 133 134 135 136 137
  138 139]
 [140 141 142 143 144 145 146 147 148 149 150 151 152 153 154 155 156 157
  158 159]
 [160 161 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177
  178 179]
 [180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
  198 199]] =============
[[  0   1   2   3   4   5   6   7   8   9]
 [ 10  11  12  13  14  15  16  17  18  19]
 [ 20  21  22  23  24  25  26  27  28  29]
 [ 30 

In [60]:
# 27. Question: Generate a large 2D array and demonstrate the use of np. reshape () and unravel () to manipulate its shape for various linear
# algebra operations. 
array_2d = np.random.randint(1, 100,(100, 50))
print(array_2d,"==========")
reshaped=array_2d.reshape(50,100)
print(reshaped,"===========")
raveled=array_2d.ravel()
print(raveled)
######################Sir se puchna h??????????????????????❓❓❓❓❓❓❓❓

[[72 31  4 ... 79 74 57]
 [67 99  3 ... 86 48 58]
 [27 60 18 ... 58 94 81]
 ...
 [10 28 27 ... 29 41 43]
 [97 22 43 ... 99 50 99]
 [43 74 38 ... 39 19 59]] ==========
[[72 31  4 ... 86 48 58]
 [27 60 18 ... 85  3 82]
 [94 79 11 ... 18 25 88]
 ...
 [ 1 97 10 ... 96  5  2]
 [34 57 36 ... 29 41 43]
 [97 22 43 ... 39 19 59]] ===========
[72 31  4 ... 39 19 59]


In [63]:
# 28. Question:Given a 6x6 matrix,use advanced indexing and slicing to extract the upper triangular part of the matrix and set the lower triangular
# part to zero. Verify the result. 
import numpy as np
matrix = np.random.randint(1, 10, size=(6, 6))
matrix




array([[6, 6, 2, 2, 7, 3],
       [1, 6, 1, 7, 4, 6],
       [4, 7, 3, 5, 7, 8],
       [9, 1, 3, 3, 9, 1],
       [3, 6, 5, 8, 5, 9],
       [8, 3, 7, 6, 2, 7]], dtype=int32)